

# Create a second Python script called guessinggame.py. In this script, you need to access the functions created in the mymodules.py script. Furthermore, this script should present the user with a guessing game. The user should be prompted to guess a number between 0 and 10. The system should then randomly generate a number between 0 and 10 using a function from mymodules.py. If the user guessed correctly, display a congratulatory message. Otherwise, display a message stating the actual number and wish them luck for their next attempt. The user should be able to play the game as many times as they want. If the user has finished playing, the system should display a message stating how many seconds they played.






























